

PROGRAM _EXIT
	(* ======================================================================== *)
	(* IO_EXIT                                                                   *)
	(* Ovaj task trenutno nema posebnu gasnu proceduru.                          *)
	(* Svi FB-ovi i I/O signali prelaze u stanje definisano runtime-om i HW-om. *)
	(* ======================================================================== *)
END_PROGRAM