TYPE
	(* Sirova i skalirana referenca/povratna vrednost proporcionalnog ventila. *)
	ST_VALVE_PV_ACT : STRUCT (* Sirova i skalirana referenca/povratna vrednost proporcionalnog ventila. *)
		iREF_RAW : INT; (* Sirova referentna vrednost izlaza. *)
		rREF : REAL; (* Skalirana referentna vrednost. *)
		iFB_RAW : INT; (* Sirova povratna vrednost polozaja. *)
		rFB_SCALED : REAL; (* Skalirani povratni polozaj ventila. *)
	END_STRUCT;
	(* Status, komande, vremena i izbor rezima automatskog ventila. *)
	ST_VALVE_ACT_TYPE : STRUCT (* Status, komande, vremena i izbor rezima automatskog ventila. *)
		iSTATUS : INT; (* Kod radnog statusa ventila. *)
		xOPEN_FB : BOOL; (* Povratna potvrda otvorenog polozaja. *)
		xCLOSE_FB : BOOL; (* Povratna potvrda zatvorenog polozaja. *)
		xREQUEST : BOOL; (* Zahtev za promenu polozaja ventila. *)
		xSET : BOOL; (* Zadata binarna komanda polozaja. *)
		xVALVE_ALARM : BOOL; (* Zbirni alarm ventila. *)
		xAlarm_RESET : BOOL; (* Zahtev za reset alarma ventila. *)
		iCounter_Act : UDINT; (* Brojac aktivacija ventila. *)
		xCounter_RESET : BOOL; (* Zahtev za reset brojaca aktivacija. *)
		T_MAX_Preclosing_ms : UDINT; (* Maksimalni timeout predzatvaranja [ms]. *)
		T_MIN_Closing_ms : UDINT; (* Minimalno vreme zatvaranja [ms]. *)
		T_MAX_Closing_ms : UDINT; (* Maksimalni timeout zatvaranja [ms]. *)
		T_MAX_Preopening_ms : UDINT; (* Maksimalni timeout predotvaranja [ms]. *)
		T_MIN_Opening_ms : UDINT; (* Minimalno vreme otvaranja [ms]. *)
		T_MAX_Opening_ms : UDINT; (* Maksimalni timeout otvaranja [ms]. *)
		T_Preopening_ms : UDINT; (* Izmereno vreme predotvaranja [ms]. *)
		T_Opening_ms : UDINT; (* Izmereno vreme otvaranja [ms]. *)
		T_Preclosing_ms : UDINT; (* Izmereno vreme predzatvaranja [ms]. *)
		T_Closing_ms : UDINT; (* Izmereno vreme zatvaranja [ms]. *)
		xMANUAL_SET : BOOL; (* Rucna komanda polozaja. *)
		xMODE_AUTO_MAN : BOOL; (* Izbor automatskog ili rucnog rezima. *)
	END_STRUCT;
	(* Osnovni udaljeni analogni senzor; IEBKB1 upisuje merenje i status. *)
	ST_SENSORS_TYPE : STRUCT (* Osnovni udaljeni analogni senzor; IEBKB1 upisuje merenje i status. *)
		_00_raw_value : INT; (* Sirova vrednost senzora. *)
		_01_value : REAL; (* Skalirana procesna vrednost. *)
		_02_status : BOOL; (* Validnost/status senzora. *)
	END_STRUCT;
	(* Prosireni udaljeni analogni senzor sa dva dodatna binarna statusa. *)
	ST_SENSORS_K_TYPE : STRUCT (* Prosireni udaljeni analogni senzor sa dva dodatna binarna statusa. *)
		_00_raw_value : INT; (* Sirova vrednost senzora. *)
		_01_value : REAL; (* Skalirana procesna vrednost. *)
		_02_status : BOOL; (* Validnost/status senzora. *)
		_03_CB_1 : BOOL; (* Dodatni binarni status CB_1. *)
		_04_CB_2 : BOOL; (* Dodatni binarni status CB_2. *)
	END_STRUCT;
	(* Udaljeni status i komande pumpe/frekventnog regulatora. *)
	ST_PUMP : STRUCT (* Udaljeni status i komande pumpe/frekventnog regulatora. *)
		x_RUN : BOOL; (* Status rada pumpe. *)
		xAL : BOOL; (* Alarm pumpe ili regulatora. *)
		xAL_RST : BOOL; (* Zahtev za reset alarma. *)
		rFR_REF_scaled : REAL; (* Skalirana referenca frekvencije [Hz]. *)
		iFR_REF_raw : INT; (* Sirova referenca frekvencije. *)
	END_STRUCT;
	(* Udaljeni status rucnog ventila sa alarmnim vremenima. *)
	ST_MAN_VALVE : STRUCT (* Udaljeni status rucnog ventila sa alarmnim vremenima. *)
		xCLOSE_FB : BOOL; (* Povratna potvrda zatvorenog polozaja. *)
		xOPEN_FB : BOOL; (* Povratna potvrda otvorenog polozaja. *)
		xALARM_RESET : BOOL; (* Zahtev za reset alarma. *)
		rALARM_DELAY_PT : REAL; (* Zadato kasnjenje alarma. *)
		rALARM_ET : REAL; (* Proteklo vreme alarmnog uslova. *)
		xALARM : BOOL; (* Zbirni alarm ventila. *)
		iSTATUS : INT; (* Kod radnog statusa ventila. *)
	END_STRUCT;
	(* Udaljeni temperaturni senzori; IEBKB1 upisuje sve vrednosti/status. *)
	Sens_Tt_type : STRUCT (* Udaljeni temperaturni senzori; IEBKB1 upisuje sve vrednosti/status. *)
		B_00 : ST_SENSORS_TYPE; (* Uredjaj/signal oznake B_00 [degC]. *)
		B_01 : ST_SENSORS_TYPE; (* Uredjaj/signal oznake B_01 [degC]. *)
		B_02 : ST_SENSORS_TYPE; (* Uredjaj/signal oznake B_02 [degC]. *)
		B_101 : ST_SENSORS_TYPE; (* Uredjaj/signal oznake B_101 [degC]. *)
		B_111 : ST_SENSORS_TYPE; (* Uredjaj/signal oznake B_111 [degC]. *)
		B_201 : ST_SENSORS_TYPE; (* Uredjaj/signal oznake B_201 [degC]. *)
	END_STRUCT;
	(* Udaljeni senzori pritiska; IEBKB1 upisuje sve vrednosti/status. *)
	Sens_Pt_type : STRUCT (* Udaljeni senzori pritiska; IEBKB1 upisuje sve vrednosti/status. *)
		B_00 : ST_SENSORS_TYPE; (* Uredjaj/signal oznake B_00 [bar]. *)
		B_01 : ST_SENSORS_TYPE; (* Uredjaj/signal oznake B_01 [bar]. *)
		B_02 : ST_SENSORS_TYPE; (* Uredjaj/signal oznake B_02 [bar]. *)
		B_101 : ST_SENSORS_TYPE; (* Uredjaj/signal oznake B_101 [bar]. *)
		B_102 : ST_SENSORS_TYPE; (* Uredjaj/signal oznake B_102 [bar]. *)
		B_103 : ST_SENSORS_TYPE; (* Uredjaj/signal oznake B_103 [bar]. *)
		B_111 : ST_SENSORS_TYPE; (* Uredjaj/signal oznake B_111 [bar]. *)
		B_112 : ST_SENSORS_TYPE; (* Uredjaj/signal oznake B_112 [bar]. *)
		B_113 : ST_SENSORS_TYPE; (* Uredjaj/signal oznake B_113 [bar]. *)
		B_140 : ST_SENSORS_TYPE; (* Uredjaj/signal oznake B_140 [bar]. *)
		B_200 : ST_SENSORS_TYPE; (* Uredjaj/signal oznake B_200 [bar]. *)
		B_201 : ST_SENSORS_TYPE; (* Uredjaj/signal oznake B_201 [bar]. *)
		B_521 : ST_SENSORS_TYPE; (* Uredjaj/signal oznake B_521 [bar]. *)
	END_STRUCT;
	(* Udaljeni statusi napajanja; IEBKB1 upisuje stanje osiguraca i izvora. *)
	Sens_Power_type : STRUCT (* Udaljeni statusi napajanja; IEBKB1 upisuje stanje osiguraca i izvora. *)
		Fuse_DC : BOOL; (* Status DC osiguraca. *)
		Fuse_AC : BOOL; (* Status AC osiguraca. *)
		Suply_24VDC_1 : BOOL; (* Status prvog 24 VDC napajanja. *)
		Suply_24VDC_2 : BOOL; (* Status drugog 24 VDC napajanja. *)
		DC_UPS_1 : BOOL; (* Status prvog DC UPS izvora. *)
		DC_UPS_2 : BOOL; (* Status drugog DC UPS izvora. *)
	END_STRUCT;
	(* Udaljeno pH merenje; IEBKB1 upisuje vrednost i status. *)
	Sens_pH_type : STRUCT (* Udaljeno pH merenje; IEBKB1 upisuje vrednost i status. *)
		proba : ST_SENSORS_TYPE; (* pH sonda. *)
	END_STRUCT;
	(* Udaljeni meraci protoka; IEBKB1 upisuje vrednosti i status. *)
	Sens_MP_type : STRUCT (* Udaljeni meraci protoka; IEBKB1 upisuje vrednosti i status. *)
		B_01 : ST_SENSORS_TYPE; (* Uredjaj/signal oznake B_01 [protok]. *)
		B_02 : ST_SENSORS_TYPE; (* Uredjaj/signal oznake B_02 [protok]. *)
	END_STRUCT;
	(* Udaljeni binarni senzori nivoa; IEBKB1 upisuje stanja. *)
	Sens_LS_type : STRUCT (* Udaljeni binarni senzori nivoa; IEBKB1 upisuje stanja. *)
		B_01 : BOOL; (* Uredjaj/signal oznake B_01. *)
		B_101 : BOOL; (* Uredjaj/signal oznake B_101. *)
		B_102 : BOOL; (* Uredjaj/signal oznake B_102. *)
		B_111 : BOOL; (* Uredjaj/signal oznake B_111. *)
		B_112 : BOOL; (* Uredjaj/signal oznake B_112. *)
		B_201 : BOOL; (* Uredjaj/signal oznake B_201. *)
		B_301 : BOOL; (* Uredjaj/signal oznake B_301. *)
	END_STRUCT;
	(* Udaljeno merenje provodnosti/kvaliteta; IEBKB1 upisuje vrednost i status. *)
	Sens_K_type : STRUCT (* Udaljeno merenje provodnosti/kvaliteta; IEBKB1 upisuje vrednost i status. *)
		proba : ST_SENSORS_TYPE; (* Merna sonda K. *)
	END_STRUCT;
	(* Zbirna struktura udaljenih IEBKB1 senzora. *)
	Sens_type : STRUCT (* Zbirna struktura udaljenih IEBKB1 senzora. *)
		Pt : Sens_Pt_type; (* Senzori pritiska. *)
		Tt : Sens_Tt_type; (* Senzori temperature. *)
		LS : Sens_LS_type; (* Binarni senzori nivoa. *)
		MP : Sens_MP_type; (* Meraci protoka. *)
		K : Sens_K_type; (* Merna sonda K. *)
		pH : Sens_pH_type; (* pH sonda. *)
		Power : Sens_Power_type; (* Statusi napajanja. *)
	END_STRUCT;
	(* Komunikacioni ugovor podstanice: PT pise Zahtev, IEBKB1 pise Status. *)
	Cntrl_Comm_Podstanica_type : STRUCT (* Komunikacioni ugovor: PT pise Zahtev, IEBKB1 pise Status. *)
		Zahtev : typPodstanicaZahtev; (* PT upisuje zahtev udaljenom IEBKB1. *)
		Parametri : typPodstanicaParametri; (* Dogovoreni radni parametri komunikacije. *)
		Status : typPodstanicaStatus; (* Udaljeni IEBKB1 upisuje procesni status. *)
	END_STRUCT;
	(* Zahtev koji PT upisuje udaljenom IEBKB1 sistemu. *)
	typPodstanicaZahtev : STRUCT (* Zahtev koji PT upisuje udaljenom IEBKB1 sistemu. *)
		ZahtevVode : BOOL; (* PT zahtev za dotok vode. *)
		NivoPrihvatnogTanka : REAL; (* PT izmereni nivo prihvatnog tanka [m]. *)
		CiljaniProtok : REAL; (* PT zadati ciljani protok. *)
		ModRada : USINT; (* PT zadati kod rezima rada. *)
	END_STRUCT;
	(* Granice protoka i frekvencije razmenjene sa udaljenim IEBKB1. *)
	typPodstanicaParametri : STRUCT (* Granice protoka i frekvencije razmenjene sa udaljenim IEBKB1. *)
		MinimalniProtok : REAL; (* Donja radna granica protoka. *)
		MaksimalniProtok : REAL; (* Gornja radna granica protoka. *)
		MinimalnaFrekvenca : REAL; (* Donja granica frekvencije [Hz]. *)
		MaksimalnaFrekvenca : REAL; (* Gornja granica frekvencije [Hz]. *)
		TolerancijaFrekvence : REAL; (* Dozvoljeno odstupanje frekvencije [Hz]. *)
	END_STRUCT;
	(* Procesni status koji udaljeni IEBKB1 upisuje PT sistemu. *)
	typPodstanicaStatus : STRUCT (* Procesni status koji udaljeni IEBKB1 upisuje PT sistemu. *)
		TrenutniProtok : REAL; (* Udaljeno izmereni trenutni protok. *)
		TrenutnaFrekvencaPumpe : REAL; (* Udaljena frekvencija pumpe [Hz]. *)
		MinimalniProtokDostignut : BOOL; (* Status dostignute minimalne granice protoka. *)
		MaksimalniProtokDostignut : BOOL; (* Status dostignute maksimalne granice protoka. *)
	END_STRUCT;
	(* Rezervisani komunikacioni prostor za BRB2. *)
	Cntrl_Comm_BRB2_type : STRUCT (* Rezervisani komunikacioni prostor za BRB2. *)
		Reserved : USINT; (* Rezervisano za buduce prosirenje ugovora. *)
	END_STRUCT;
	(* Zbirni komunikacioni ugovor upravljanja. *)
	Cntrl_Comm_type : STRUCT (* Zbirni komunikacioni ugovor upravljanja. *)
		Podstanica : Cntrl_Comm_Podstanica_type; (* Ugovor PT podstanice i IEBKB1. *)
		BRB2 : Cntrl_Comm_BRB2_type; (* Rezervisani BRB2 komunikacioni deo. *)
	END_STRUCT;
	(* Zbirni kontrolni podaci komunikacije IEBKB1. *)
	Cntrl_type : STRUCT (* Zbirni kontrolni podaci komunikacije IEBKB1. *)
		proba : BOOL; (* Pomocni komunikacioni/kontrolni signal. *)
		State : INT; (* Kod trenutnog kontrolnog stanja. *)
		Comm : Cntrl_Comm_type; (* Strukturirani komunikacioni ugovor. *)
	END_STRUCT;
	(* Udaljeni rucni ventili; B_x oznake ne odredjuju fizicki identitet. *)
	Act_RV_type : STRUCT (* Udaljeni rucni ventili; B_x fizicki identitet nije potvrdjen. *)
		B_01 : ST_MAN_VALVE; (* Uredjaj/signal oznake B_01. *)
		B_02 : ST_MAN_VALVE; (* Uredjaj/signal oznake B_02. *)
		B_03 : ST_MAN_VALVE; (* Uredjaj/signal oznake B_03. *)
		B_04 : ST_MAN_VALVE; (* Uredjaj/signal oznake B_04. *)
		B_06 : ST_MAN_VALVE; (* Uredjaj/signal oznake B_06. *)
		B_07 : ST_MAN_VALVE; (* Uredjaj/signal oznake B_07. *)
		B_08 : ST_MAN_VALVE; (* Uredjaj/signal oznake B_08. *)
		B_09 : ST_MAN_VALVE; (* Uredjaj/signal oznake B_09. *)
		B_10 : ST_MAN_VALVE; (* Uredjaj/signal oznake B_10. *)
		B_11 : ST_MAN_VALVE; (* Uredjaj/signal oznake B_11. *)
		B_21 : ST_MAN_VALVE; (* Uredjaj/signal oznake B_21. *)
		B_22 : ST_MAN_VALVE; (* Uredjaj/signal oznake B_22. *)
		B_23 : ST_MAN_VALVE; (* Uredjaj/signal oznake B_23. *)
		B_221 : ST_MAN_VALVE; (* Uredjaj/signal oznake B_221. *)
	END_STRUCT;
	(* Udaljeni proporcionalni ventili; B_x oznake ne odredjuju fizicki identitet. *)
	Act_PV_type : STRUCT (* Udaljeni proporcionalni ventili; B_x fizicki identitet nije potvrdjen. *)
		B_01 : ST_VALVE_PV_ACT; (* Uredjaj/signal oznake B_01. *)
		B_201 : ST_VALVE_PV_ACT; (* Uredjaj/signal oznake B_201. *)
	END_STRUCT;
	(* Udaljene pumpe; B_x oznake ne odredjuju fizicki identitet. *)
	Act_Pu_type : STRUCT (* Udaljene pumpe; B_x fizicki identitet nije potvrdjen. *)
		B_101 : ST_PUMP; (* Uredjaj/signal oznake B_101. *)
		B_111 : ST_PUMP; (* Uredjaj/signal oznake B_111. *)
		B_201 : ST_PUMP; (* Uredjaj/signal oznake B_201. *)
		B_211 : ST_PUMP; (* Uredjaj/signal oznake B_211. *)
		B_RB1 : ST_PUMP; (* Uredjaj/signal oznake B_RB1. *)
	END_STRUCT;
	(* Udaljeni automatski ventili; B_x oznake ne odredjuju fizicki identitet. *)
	Act_AV_type : STRUCT (* Udaljeni automatski ventili; B_x fizicki identitet nije potvrdjen. *)
		B_00 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_00. *)
		B_02 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_02. *)
		B_100 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_100. *)
		B_101 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_101. *)
		B_102 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_102. *)
		B_103 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_103. *)
		B_104 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_104. *)
		B_105 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_105. *)
		B_106 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_106. *)
		B_107 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_107. *)
		B_108 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_108. *)
		B_111 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_111. *)
		B_112 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_112. *)
		B_113 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_113. *)
		B_114 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_114. *)
		B_115 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_115. *)
		B_116 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_116. *)
		B_117 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_117. *)
		B_118 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_118. *)
		B_200 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_200. *)
		B_201 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_201. *)
		B_202 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_202. *)
		B_203 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_203. *)
		B_204 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_204. *)
		B_205 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_205. *)
		B_211 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_211. *)
		B_212 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_212. *)
		B_213 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_213. *)
		B_214 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_214. *)
		B_215 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_215. *)
		B_220 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_220. *)
		B_301 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_301. *)
		B_U22 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_U22. *)
		B_U23 : ST_VALVE_ACT_TYPE; (* Uredjaj/signal oznake B_U23. *)
	END_STRUCT;
	(* Zbirna struktura udaljenih IEBKB1 aktuatora. *)
	Act_type : STRUCT (* Zbirna struktura udaljenih IEBKB1 aktuatora. *)
		AV : Act_AV_type; (* Automatski ventili. *)
		RV : Act_RV_type; (* Rucni ventili. *)
		PV : Act_PV_type; (* Proporcionalni ventili. *)
		Pu : Act_Pu_type; (* Pumpe. *)
	END_STRUCT;
	(* Kompletan IEBKB1 komunikacioni snapshot aktuatora, senzora i kontrole. *)
	IEB_KB1_type : STRUCT (* Kompletan IEBKB1 komunikacioni snapshot aktuatora, senzora i kontrole. *)
		Act : Act_type; (* Udaljeni statusi/komande aktuatora. *)
		Sens : Sens_type; (* Senzore i statuse upisuje udaljeni IEBKB1. *)
		Cntrl : Cntrl_type; (* PT/IEBKB1 dvosmerni kontrolni ugovor. *)
	END_STRUCT;
END_TYPE