TYPE
	typPGRadTrendCursor : 	STRUCT (* HMI stanje vremenske ose, kursora i procesnih vrednosti trenda Podstanice. *)
			Position : REAL; (* Normalizovana pozicija kursora: 0.0 = levo, 1.0 = desno. *)
			Time : UDINT; (* Proteklo vreme od pocetka trend zapisa na poziciji kursora [ms]. *)
			RecordingStart : DATE_AND_TIME; (* Apsolutno vreme pocetka referentnog trend zapisa. *)
			DateTime : DATE_AND_TIME; (* Apsolutni datum i vreme uzorka na poziciji kursora. *)
			ViewStart : DATE_AND_TIME; (* Leva granica trenutno prikazanog vremenskog prozora. *)
			ViewSpan : DINT; (* Sirina prikazanog vremenskog prozora [s]. *)
			AxisMode : UINT; (* VC time-scale mod: 0 = zadati prozor bez automatskog pomeranja. *)
			PreviousViewSpan : DINT; (* Prethodna sirina prozora za promenu zoom-a bez skoka. *)
			FollowNow : BOOL; (* TRUE = desna ivica prozora prati trenutno vreme. *)
			CmdBack : BOOL; (* Jednokratni zahtev za prethodni vremenski prozor. *)
			CmdForward : BOOL; (* Jednokratni zahtev za sledeci vremenski prozor. *)
			CmdNow : BOOL; (* Jednokratni zahtev za povratak na najnovije podatke. *)
			AxisTime0 : DATE_AND_TIME; (* Pocetak prikazanog vremenskog prozora. *)
			AxisTime1 : DATE_AND_TIME; (* Prva unutrasnja vremenska oznaka ose. *)
			AxisTime2 : DATE_AND_TIME; (* Druga unutrasnja vremenska oznaka ose. *)
			AxisTime3 : DATE_AND_TIME; (* Treca unutrasnja vremenska oznaka ose. *)
			AxisTime4 : DATE_AND_TIME; (* Cetvrta unutrasnja vremenska oznaka ose. *)
			AxisTime5 : DATE_AND_TIME; (* Peta unutrasnja vremenska oznaka ose. *)
			AxisTime6 : DATE_AND_TIME; (* Sesta unutrasnja vremenska oznaka ose. *)
			AxisTime7 : DATE_AND_TIME; (* Sedma unutrasnja vremenska oznaka ose. *)
			AxisTime8 : DATE_AND_TIME; (* Kraj prikazanog vremenskog prozora. *)
			Status : UINT; (* VC status trend kursora; bit 10 oznacava validan Cursor 1. *)
			Nivo : REAL; (* Nivo prihvatnog tanka na poziciji kursora [m]. *)
			Pritisak : REAL; (* PT05 pritisak potisa pumpe na poziciji kursora [bar]. *)
			Protok : REAL; (* Protok ka bazenima na poziciji kursora [l/s]. *)
			TT01 : REAL; (* Temperatura TT01 na poziciji kursora [degC]. *)
			TT03 : REAL; (* Temperatura u prihvatnom tanku TT03 na poziciji kursora [degC]. *)
			TT04 : REAL; (* Temperatura TT04 na poziciji kursora [degC]. *)
			TT05 : REAL; (* Temperatura TT05 na poziciji kursora [degC]. *)
			TT06 : REAL; (* Temperatura TT06 na poziciji kursora [degC]. *)
		END_STRUCT;
END_TYPE
