TYPE
	typVezaPGRadBRB2 : 	STRUCT  (* Dvosmerni procesni ugovor: PT pise komande, BRB2 pise statuse. *)
			RadKaPodstanici : BOOL; (* PT izbor rute BRB2 ka podstanici; prihvata se samo u BRB2 standby. *)
			ManualMode : BOOL; (* Dozvola servisnog rucnog rezima. *)
			ManualSequence : USINT; (* Izabrana servisna sekvenca. *)
			ManualStart : BOOL; (* Impuls za pokretanje servisne sekvence. *)
			ManualStop : BOOL; (* Impuls za bezbedan prekid servisne sekvence. *)
			ManualNextStep : BOOL; (* Impuls za sledeci dozvoljeni podkorak. *)
			ManualAbort : BOOL; (* Impuls za povratak u Standby. *)
			CommandCounter : UDINT; (* Monotoni PT brojac za BRB2 watchdog komandi. *)
			ZahtevStarta : BOOL; (* PT zahtev BRB2 za pripremu i start bunarske pumpe. *)
			ZahtevZaustavljanja : BOOL; (* PT zahtev BRB2 za kontrolisano zaustavljanje. *)
			VentiliPodstaniceZatvoreni : BOOL; (* PT potvrda zatvorenosti PG_PV01, PG_PV02 i PG_PV05. *)
			PritisakIEBKB1 : REAL; (* PT prosledjuje stvarni pritisak IEBKB1 odredista [bar]. *)
			PodstanicaURezimuRada : BOOL; (* PT tank je na nivou i izabrana izlazna pumpa je stvarno u radu. *)
			RegulationMode : USINT; (* PT izbor BRB2 petlje preko AsIMA: 0=neaktivna, 1=protok, 2=nivo, 3=temperatura. *)
			RegulationPV : REAL; (* PT prosledjuje procesnu vrednost aktivne petlje. *)
			RegulationSP : REAL; (* PT prosledjuje zadatu vrednost aktivne petlje. *)
			RegulationPVValid : BOOL; (* PT potvrda validnosti aktivne procesne vrednosti. *)
			RegulationInvert : BOOL; (* PT zahtev za obrtanje smera regulacije. *)
			NivoPrihvatniSud : REAL; (* Nivo prihvatnog suda koji se salje BRB2 kao PV moda 2 [m]. *)
			StatusCounter : UDINT; (* Monotoni BRB2 brojac za PT watchdog statusa. *)
			BRB2Fault : BOOL; (* Zbirni fault aktivne BRB2 pumpe ili regulatora. *)
			BRB2FaultCode : USINT; (* Stabilan kod BRB2 fault uzroka za Podstanicu. *)
			RegulationPVFault : BOOL; (* Aktivni PV nije validan duze od dozvoljenog vremena. *)
			PumpaAktivna : BOOL; (* BRB2 stvarna potvrda da je RB2_01 u InRun stanju. *)
			IspiranjeProtokDostignut : BOOL; (* BRB2 stvarni protok je dostigao ProtokIspiranja. *)
			IspiranjeMinTrajanjeDostignuto : BOOL; (* BRB2 je na ProtokIspiranja najmanje T_IspiranjeMin. *)
			StopSPDostignut : BOOL; (* BRB2 potvrda dostignutog FR_MinZeroFlow. *)
			RB2V01Zatvoren : BOOL; (* BRB2 potvrda zatvorenog RB2_V01 za IEBKB1 granu. *)
			RB2V02Zatvoren : BOOL; (* BRB2 potvrda zatvorenog RB2_V02. *)
		END_STRUCT;
		typBRB2CommWatchdog : 	STRUCT (* Lokalna memorija i validnost watchdog-a udaljenog brojaca. *)
			LastCounter : UDINT; (* Poslednji primljeni udaljeni brojac. *)
			ReceivedOnce : BOOL; (* TRUE nakon prve registrovane promene udaljenog brojaca. *)
			ReceiveTimeout : TON; (* Timeout bez promene udaljenog brojaca. *)
			Valid : BOOL; (* TRUE dok se udaljeni brojac menja unutar 5 s. *)
		END_STRUCT;
		typIEBKB1PreparedInterface : 	STRUCT  (* Lokalno pripremljen ugovor; jos nije deo postojeceg IEB wire-layout-a. *)
			Enable : BOOL; (* Dozvola koriscenja prosirenog IEBKB1 ugovora. *)
			InterfaceReady : BOOL; (* Verzija udaljenog PLC-a podrzava sva sledeca polja. *)
			CommValid : BOOL; (* AsIMA komunikacija je validna. *)
			HeartbeatValid : BOOL; (* Heartbeat se menja unutar dozvoljenog vremena. *)
			HeartbeatCounter : UDINT; (* Poslednji primljeni heartbeat brojac. *)
			Fault : BOOL; (* IEBKB1 prijavljuje aktivnu gresku. *)
			CommandAccepted : BOOL; (* IEBKB1 je prihvatio poslednju procesnu komandu. *)
			PumpRunning : BOOL; (* IEBKB1 potvrda stvarnog rada pumpe. *)
			FlowValid : BOOL; (* IEBKB1 potvrda validnog merenja protoka. *)
		END_STRUCT;
END_TYPE
