TYPE
	(* ======================================================================== *)
	(* Glavni agregatni tip za VFD instancu                                    *)
	(* ======================================================================== *)
	VFD_type : 	STRUCT (* Glavna agregatna struktura jedne VFD instance. *)
		cmds : vfd_commands;              (* Komandni zahtevi ka frekventnom regulatoru – sve upravljačke komande za VFD instancu. *)
		params : vfd_set_parameters;      (* Procesni setpoint-i i dinamika (acc/dec) – parametri zadavanja brzine, ubrzanja i usporenja. *)
		mapping : vfd_mapping;            (* Niskonivo mapiranje I/O i fieldbus registara – fizičko/logičko mapiranje signala. *)
		states : vfd_states;              (* Dekodirana operativna stanja regulatora – statusni bitovi i stanja rada. *)
		status : vfd_status;              (* Aktuelne merene vrednosti regulatora/motora – procesni izlazi. *)
		errorID : UINT;                   (* Numerički kod greške iz komunikacije/drive-a – za dijagnostiku. *)
		errorText : STRING[40];           (* Kratak tekstualni opis greške za HMI – olakšava korisničku dijagnostiku. *)
		settings : vfd_settings_param;    (* Konfiguracija metode rada i granica – podešavanja instance. *)
		errorMgmt : vfd_errorMgmt;        (* Statistika i trajanje prekida komunikacije – monitoring pouzdanosti. *)
	END_STRUCT;

	(* ======================================================================== *)
	(* Procesni status izlazi                                                   *)
	(* ======================================================================== *)
	vfd_status : 	STRUCT (* Procesni status izlaza – merene vrednosti pogona. *)
		act_velocity : REAL;      (* Trenutna brzina motora [r/min]. *)
		act_power : REAL;         (* Trenutna snaga motora [kW]. *)
		act_torque : REAL;        (* Trenutni obrtni moment [Nm] – zavisi od mapiranja drive-a. *)
		act_voltage : REAL;       (* Trenutni napon motora [V]. *)
		act_freq : REAL;          (* Trenutna frekvencija izlaza [Hz]. *)
		act_current : REAL;       (* Trenutna struja motora [A]. *)
	END_STRUCT;

	(* ======================================================================== *)
	(* Dekodirana stanja rada VFD                                               *)
	(* ======================================================================== *)
	vfd_states : 	STRUCT (* Dekodirana radna stanja VFD-a i statusni bitovi. *)
		PWR_ON : BOOL := FALSE;              (* Napajanje/drive aktivan – glavni naponski izvor uključen. *)
		ALARM : BOOL := FALSE;               (* Alarm stanje bez hard fault latch-a – signalizacija upozorenja. *)
		FAULT : BOOL := FALSE;               (* Fault stanje regulatora – kritična greška, rad onemogućen. *)
		TUNING : BOOL := FALSE;              (* Aktivno tuning/samopodešavanje – automatska optimizacija parametara. *)
		READY : BOOL := FALSE;               (* Drive spreman za komandu rada – svi uslovi za start su ispunjeni. *)
		PREOPERATIONAL : BOOL := FALSE;      (* Pre-run tranziciono stanje – prelazna faza pre rada. *)
		JOG : BOOL := FALSE;                 (* Jog režim aktivan – ručno pokretanje za podešavanje. *)
		RUN : BOOL := FALSE;                 (* Kontinualni rad aktivan – normalan režim pogona. *)
		STOPPING : BOOL := FALSE;            (* U toku kontrolisano zaustavljanje – sekvenca zaustavljanja. *)
		STOPED : BOOL := FALSE;              (* Zaustavljen (zadržan originalni naziv) – pogon je stao. *)
		OVERCURRENT_PROTECT : BOOL := FALSE; (* Aktivna zaštita od prekostruje – zaštitna funkcija. *)
		state_word : UINT := 0;              (* Sirovi/dekodirani state kod za internu obradu – za naprednu dijagnostiku. *)
	END_STRUCT;

	(* ======================================================================== *)
	(* Parametri setovanja                                                       *)
	(* ======================================================================== *)
	vfd_set_parameters : 	STRUCT (* Parametri zadavanja brzine i dinamike pogona. *)
		Freq : REAL;         (* Glavna zadavana frekvencija [Hz] – opseg 0–100.00. *)
		Jog_freq : REAL;     (* Posebna jog frekvencija [Hz] – za ručno pokretanje. *)
		Dec : REAL;          (* Vreme/uslov usporavanja [s] – prema mapiranju drive-a. *)
		Acc : REAL;          (* Vreme/uslov ubrzavanja [s] – prema mapiranju drive-a. *)
	END_STRUCT;

	(* ======================================================================== *)
	(* Grupisano mapiranje po metodi upravljanja                                *)
	(* ======================================================================== *)
	vfd_mapping : 	STRUCT (* Grupisano mapiranje signala po metodi upravljanja. *)
		DIO : vfd_maping_DIO;              (* Diskretno/analogno mapiranje preko I/O signala – osnovni digitalni/analogni signali. *)
		CanOpenATV : vfd_maping_CanOpenATV;(* CANopen mapiranje za ATV varijantu – komunikacija sa ATV uređajem. *)
		CanOpen : vfd_maping_CanOpenENC;   (* CANopen mapiranje za ENC varijantu – komunikacija sa ENC uređajem. *)
	END_STRUCT;

	(* ======================================================================== *)
	(* DIO mapiranje                                                             *)
	(* ======================================================================== *)
	vfd_maping_DIO : 	STRUCT (* DIO mapiranje komandi i povratnih signala. *)
		w_run_fwd : BOOL;         (* Komanda: rad napred – pokretanje motora unapred. *)
		w_run_rev : BOOL;         (* Komanda: rad nazad – pokretanje motora unazad. *)
		w_jog_fwd : BOOL;         (* Komanda: jog napred – ručno pokretanje unapred. *)
		w_jog_rev : BOOL;         (* Komanda: jog nazad – ručno pokretanje unazad. *)
		w_Stop : BOOL;            (* Komanda: standard stop – normalno zaustavljanje. *)
		w_faststop : BOOL;        (* Komanda: brzi stop – hitno zaustavljanje. *)
		w_reset : BOOL;           (* Komanda: reset greške – resetuje fault/grešku. *)
		w_freq : INT;             (* Upisana frekvencija/komanda (raw) – zadavanje brzine. *)
		r_freq : INT;             (* Pročitana frekvencija (raw) – povratna informacija. *)
		r_OverCurrentProtect : BOOL; (* Povratni signal zaštite od prekostruje – signalizacija zaštite. *)
		r_error : BOOL;           (* Povratni signal opšte greške drive-a – signalizacija kvara. *)
	END_STRUCT;

	(* ======================================================================== *)
	(* CANopen ATV mapiranje                                                     *)
	(* ======================================================================== *)
	vfd_maping_CanOpenATV : 	STRUCT (* CANopen mapiranje za ATV varijantu pogona. *)
		StatusWord : UINT;            (* Status reč sa CANopen uređaja – statusni bitovi pogona. *)
		CtrlWord : UINT;              (* Komandna reč ka CANopen uređaju – upravljački zahtevi. *)
		r_freq : INT;                 (* Pročitana frekvencija (raw skala ATV) – povratna vrednost. *)
		r_power : INT;                (* Pročitana snaga (raw/procenat, zavisi od mapiranja). *)
		r_current : UINT;             (* Pročitana struja (raw) – trenutna potrošnja. *)
		r_torque : INT;               (* Pročitani moment (raw) – trenutni obrtni moment. *)
		r_voltage : UINT;             (* Pročitan napon (raw) – trenutni napon. *)
		r_velocity : INT;             (* Pročitana brzina (raw) – trenutna brzina. *)
		r_CtrlWord : UINT;            (* Echo/feedback komandne reči – povratna informacija. *)
		r_errorCode : UINT;           (* Kod greške prijavljen od drive-a – dijagnostika. *)
		r_RatedMotorPower : UINT;     (* Nominalna snaga motora pročitana iz drive-a. *)
		r_OverCurrentProtect : BOOL;  (* Povratni signal overcurrent zaštite – signalizacija zaštite. *)
		w_TargetVelocity : INT;       (* Upis target brzine – zadavanje željene brzine. *)
		w_acc : UINT;                 (* Upis parametra acc – zadavanje ubrzanja. *)
		w_dec : UINT;                 (* Upis parametra dec – zadavanje usporenja. *)
		ControlEffort : INT;          (* Interni/eksterni effort signal (mapiran) – napor kontrole. *)
		ModuleStatusOK : BOOL;        (* Status komunikacionog modula za ATV kanal – TRUE=modul OK. *)
	END_STRUCT;

	(* ======================================================================== *)
	(* CANopen ENC mapiranje                                                     *)
	(* ======================================================================== *)
	vfd_maping_CanOpenENC : 	STRUCT (* CANopen mapiranje za ENC varijantu pogona. *)
		StatusWord : UINT;            (* Status reč sa CANopen uređaja – statusni bitovi pogona. *)
		CtrlWord : UINT;              (* Komandna reč ka CANopen uređaju – upravljački zahtevi. *)
		r_freq : UINT;                (* Pročitana frekvencija (raw) – povratna vrednost. *)
		r_power : UINT;               (* Pročitana snaga (raw) – trenutna snaga. *)
		r_current : UINT;             (* Pročitana struja (raw) – trenutna potrošnja. *)
		r_torque : UINT;              (* Pročitani moment (raw) – trenutni obrtni moment. *)
		r_voltage : UINT;             (* Pročitan napon (raw) – trenutni napon. *)
		r_velocity : UINT;            (* Pročitana brzina (raw) – trenutna brzina. *)
		r_CtrlWord : UINT;            (* Echo/feedback komandne reči – povratna informacija. *)
		r_errorCode : UINT;           (* Kod greške prijavljen od drive-a – dijagnostika. *)
		r_OverCurrentProtect : BOOL;  (* Povratni signal overcurrent zaštite – signalizacija zaštite. *)
		w_acc : UINT;                 (* Upis parametra acc – zadavanje ubrzanja. *)
		w_dec : UINT;                 (* Upis parametra dec – zadavanje usporenja. *)
		w_freq : UINT;                (* Upis komandne frekvencije (raw) – zadavanje brzine. *)
		ModuleStatusOK : BOOL;        (* Status komunikacionog modula za ENC kanal – TRUE=modul OK. *)
	END_STRUCT;

	(* ======================================================================== *)
	(* Upravljanje greskama komunikacije                                         *)
	(* ======================================================================== *)
	vfd_errorMgmt : 	STRUCT (* Evidencija i status prekida komunikacije. *)
		Last_time : DATE_AND_TIME;    (* Vreme poslednjeg završenog komunikacionog ispada – za istoriju. *)
		Last_Duration : TIME;         (* Trajanje poslednjeg ispada [ms]. *)
		Counter_errors : DINT;        (* Broj registrovanih prekida komunikacije – ukupno. *)
		Max_duration : TIME;          (* Najduže trajanje pojedinačnog prekida [ms]. *)
		StatusOK : BOOL;              (* Trenutni status komunikacije (TRUE=OK). *)
	END_STRUCT;

	(* ======================================================================== *)
	(* Parametri konfiguracije instance                                           *)
	(* ======================================================================== *)
	vfd_settings_param : 	STRUCT (* Konfiguracioni parametri rada i granice instance. *)
		METOD_OF_CONTROL : USINT;         (* Izabrani metod upravljanja (DIO/CANopen varijante) – način kontrole. *)
		MIN_Freq : REAL;                  (* Minimalna dozvoljena frekvencija [Hz]. *)
		MAX_Freq : REAL;                  (* Maksimalna dozvoljena frekvencija [Hz]. *)
		MAX_Velocity : REAL;              (* Maksimalna brzina motora [r/min]. *)
		RatedMotorPower : REAL;           (* Nominalna snaga motora sa natpisne pločice [kW]. *)
		HaveOverCurrentProtection : BOOL; (* TRUE=ima zaštitu od prekostruje, FALSE=nema. *)
	END_STRUCT;

	(* ======================================================================== *)
	(* Komande upravljanja                                                       *)
	(* ======================================================================== *)
	vfd_commands : 	STRUCT (* Upravljačke komande za rad VFD instance. *)
		Enable : BOOL;                (* Glavni enable bloka i komandi – omogućava rad instance. *)
		FastStop : BOOL;              (* Prioritetna komanda brzog zaustavljanja – hitno zaustavljanje. *)
		Stop : BOOL;                  (* Standardna stop komanda – normalno zaustavljanje. *)
		Run_fwd : BOOL;               (* Kontinualni rad napred – pokretanje motora unapred. *)
		Run_rev : BOOL;               (* Kontinualni rad nazad – pokretanje motora unazad. *)
		Jog_rev : BOOL;               (* Jog nazad – ručno pokretanje unazad. *)
		Jog_fwd : BOOL;               (* Jog napred – ručno pokretanje unapred. *)
		en_autoReset : BOOL := TRUE;  (* Automatski reset odabranih fault uslova – automatsko otklanjanje grešaka. *)
		Reset : BOOL;                 (* Ručni reset fault/alarm stanja – manuelno otklanjanje grešaka. *)
	END_STRUCT;
END_TYPE
