(* ============================================================================ *)
(* BR_LIB - CENTRALNI PREGLED SVIH DATA TYPE DEKLARACIJA                       *)
(* Sadrzi TYPE deklaracije iz FB-ova koje smo standardizovali.                  *)
(* Namena: referenca, copy/paste i priprema za eventualno centralno tipiziranje.*)
(* ============================================================================ *)

TYPE
	(* ======================================================================== *)
	(* FB_AI_01_DI_01                                                         *)
	(* ======================================================================== *)
	typInAI01_DI01 : STRUCT (* Ulazna struktura FB_AI_01_DI_01. *)
		Enable : BOOL; (* Globalni enable FB-a *)
		RawValue : INT; (* Raw vrednost sa AI kanala *)
		ManualValue : REAL; (* Rucno zadana skalirana vrednost *)
		EnableManual : BOOL; (* TRUE = koristi ManualValue umesto RawValue *)
		ResetAlarm : BOOL; (* Reset latched alarma *)
		ManualAlarm : BOOL; (* Spoljasnji/manual alarm signal *)
		UnderRange : BOOL; (* Sistemski signal: ulaz ispod opsega *)
		OverRange : BOOL; (* Sistemski signal: ulaz iznad opsega *)
		TransmitterStatus : BOOL; (* TRUE = transmiter ispravan; FALSE = fault sa transmitera *)
	END_STRUCT;

	typParAI01_DI01 : STRUCT (* Parametarska struktura FB_AI_01_DI_01. *)
		RawMin : INT; (* Donja granica raw opsega *)
		RawMax : INT; (* Gornja granica raw opsega *)
		ScaledMin : REAL; (* Donja granica skaliranog opsega *)
		ScaledMax : REAL; (* Gornja granica skaliranog opsega *)
		EnableStatusCheck : BOOL; (* TRUE = koristi TransmitterStatus u logici; FALSE = ignorise statusni DI signal *)
		UnitOfMeasure : STRING[80]; (* Jedinica mere za izlaznu vrednost *)
	END_STRUCT;

	typOutAI01_DI01 : STRUCT (* Izlazna struktura FB_AI_01_DI_01. *)
		ScaledValue : REAL; (* Skalirana inzenjerska vrednost *)
		Status : BOOL; (* TRUE = bez alarma i Enable=TRUE *)
		State : USINT; (* Numericki kod stanja *)
		State_comment : STRING[80]; (* Trenutni opis stanja *)
		UnitOfMeasureOut : STRING[80]; (* Prosledjena jedinica mere *)
		TransmitterStatusIn : BOOL; (* Kopija ulaznog statusnog signala transmitera za HMI/SCADA *)
	END_STRUCT;

	typIntAI01_DI01 : STRUCT (* Interna radna struktura FB_AI_01_DI_01. *)
		FaultLatched : BOOL; (* Memorisan alarm dok se ne resetuje *)
		FaultCondition : BOOL; (* Trenutni fault uslov u ovom scan-u *)
		ScaleSpanRaw : REAL; (* Raspon raw opsega *)
		ScaleSpanScaled : REAL; (* Raspon skaliranog opsega *)
		ManualValueLimited : REAL; (* Ogranicena manual vrednost na parametarski opseg *)
		ResetRequest : BOOL; (* Interna kopija reset komande *)
	END_STRUCT;

	typConstAI01_DI01 : STRUCT (* Struktura konstanti i state tekstova FB_AI_01_DI_01. *)
		ST_DISABLED : USINT := 0; (* Blok onemogucen (Enable=FALSE). *)
		ST_ACTIVE : USINT := 1; (* Normalan rad bez alarma. *)
		ST_UNDERRANGE : USINT := 2; (* Raw vrednost ispod RawMin granice. *)
		ST_OVERRANGE : USINT := 3; (* Raw vrednost iznad RawMax granice. *)
		ST_FAULT : USINT := 4; (* Latched fault stanje u automatskom radu. *)
		ST_MANUAL : USINT := 5; (* Aktivno manuelno zadavanje bez fault-a. *)
		ST_MANUAL_FAULT : USINT := 6; (* Manuelni rad uz aktivan latched fault. *)
		ST_TRANSMITTER_STATUS_0 : USINT := 7; (* Statusni DI transmitera je FALSE. *)
		CMT_DISABLED : STRING[80] := 'Stanje 0: transmiter neaktivan (Enable=FALSE), izlaz je na 0.0.'; (* Tekstualni opis stanja ST_DISABLED. *)
		CMT_ACTIVE : STRING[80] := 'Stanje 1: normalan rad, ulaz je u dozvoljenom opsegu, bez alarma.'; (* Tekstualni opis stanja ST_ACTIVE. *)
		CMT_UNDERRANGE : STRING[80] := 'Stanje 2: ulazna raw vrednost je ispod definisanog minimuma (RawMin).'; (* Tekstualni opis stanja ST_UNDERRANGE. *)
		CMT_OVERRANGE : STRING[80] := 'Stanje 3: ulazna raw vrednost je iznad definisanog maksimuma (RawMax).'; (* Tekstualni opis stanja ST_OVERRANGE. *)
		CMT_FAULT : STRING[80] := 'Stanje 4: prisutan je alarm (latched), potreban je ResetAlarm za potvrdu.'; (* Tekstualni opis stanja ST_FAULT. *)
		CMT_MANUAL : STRING[80] := 'Stanje 5: aktivan rucni rezim, ScaledValue dolazi iz ManualValue.'; (* Tekstualni opis stanja ST_MANUAL. *)
		CMT_MANUAL_FAULT : STRING[80] := 'Stanje 6: aktivan rucni rezim i istovremeno prisutan latched alarm.'; (* Tekstualni opis stanja ST_MANUAL_FAULT. *)
		CMT_TRANSMITTER_STATUS_0 : STRING[80] := 'Stanje 7: statusni DI signal transmitera je 0 (EnableStatusCheck=TRUE).'; (* Tekstualni opis stanja ST_TRANSMITTER_STATUS_0. *)
	END_STRUCT;

	typAI01_DI01 : STRUCT (* Agregatna struktura svih sekcija za FB_AI_01_DI_01. *)
		Input : typInAI01_DI01; (* Ulazni signali i komande bloka. *)
		Param : typParAI01_DI01; (* Parametri skaliranja i ponasanja. *)
		Output : typOutAI01_DI01; (* Izlazi, status i state informacije. *)
		Internal : typIntAI01_DI01; (* Interna radna memorija. *)
		Constant : typConstAI01_DI01; (* Konstante state kodova i tekstova. *)
	END_STRUCT;

	(* ======================================================================== *)
	(* FB_AI_01_DI_01_DO_02                                                    *)
	(* ======================================================================== *)
	typInAI01_DI01_DO02 : STRUCT (* Ulazna struktura FB_AI_01_DI_01_DO_02. *)
		Enable : BOOL; (* Globalni enable FB-a *)
		RawValue : INT; (* Raw vrednost sa AI kanala *)
		ManualValue : REAL; (* Rucno zadana skalirana vrednost *)
		EnableManual : BOOL; (* TRUE = koristi ManualValue umesto RawValue *)
		ResetAlarm : BOOL; (* Reset latched alarma *)
		ManualAlarm : BOOL; (* Spoljasnji/manual alarm signal *)
		UnderRange : BOOL; (* Sistemski signal: ulaz ispod opsega *)
		OverRange : BOOL; (* Sistemski signal: ulaz iznad opsega *)
		TransmitterStatus : BOOL; (* TRUE = transmiter ispravan; FALSE = fault sa transmitera *)
		RangeSelect : USINT; (* Izbor opsega 1..4 *)
		RangeSettleTime : TIME; (* Vreme stabilizacije nakon promene opsega *)
	END_STRUCT;

	typParAI01_DI01_DO02 : STRUCT (* Parametarska struktura FB_AI_01_DI_01_DO_02. *)
		RawMin : INT; (* Donja granica raw opsega *)
		RawMax : INT; (* Gornja granica raw opsega *)
		ScaledMin_R1 : REAL; (* Donja granica skaliranog opsega R1 *)
		ScaledMax_R1 : REAL; (* Gornja granica skaliranog opsega R1 *)
		ScaledMin_R2 : REAL; (* Donja granica skaliranog opsega R2 *)
		ScaledMax_R2 : REAL; (* Gornja granica skaliranog opsega R2 *)
		ScaledMin_R3 : REAL; (* Donja granica skaliranog opsega R3 *)
		ScaledMax_R3 : REAL; (* Gornja granica skaliranog opsega R3 *)
		ScaledMin_R4 : REAL; (* Donja granica skaliranog opsega R4 *)
		ScaledMax_R4 : REAL; (* Gornja granica skaliranog opsega R4 *)
		UnitOfMeasure : STRING[80]; (* Jedinica mere za izlaznu vrednost *)
	END_STRUCT;

	typOutAI01_DI01_DO02 : STRUCT (* Izlazna struktura FB_AI_01_DI_01_DO_02. *)
		ScaledValue : REAL; (* Skalirana inzenjerska vrednost *)
		Status : BOOL; (* TRUE = bez alarma i Enable=TRUE *)
		State : USINT; (* Numericki kod stanja *)
		State_comment : STRING[80]; (* Trenutni opis stanja *)
		UnitOfMeasureOut : STRING[80]; (* Prosledjena jedinica mere *)
		TransmitterStatusIn : BOOL; (* Kopija ulaznog statusnog signala transmitera za HMI/SCADA *)
		ActiveRange : USINT; (* Trenutno aktivan opseg 1..4 *)
		RangeComment : STRING[40]; (* Opis aktivnog opsega *)
		RangeBit0_out : BOOL; (* DO bit 0 za izbor opsega *)
		RangeBit1_out : BOOL; (* DO bit 1 za izbor opsega *)
		RangeChanging : BOOL; (* TRUE tokom stabilizacije promene opsega *)
		FaultProcessOut : BOOL; (* TRUE kada je aktivan procesni fault *)
		FaultConfigOut : BOOL; (* TRUE kada je aktivan konfiguracioni fault *)
	END_STRUCT;

	typIntAI01_DI01_DO02 : STRUCT (* Interna radna struktura FB_AI_01_DI_01_DO_02. *)
		FaultLatched : BOOL; (* Memorisan alarm dok se ne resetuje *)
		FaultCondition : BOOL; (* Trenutni fault uslov u ovom scan-u *)
		FaultProcess : BOOL; (* Procesni fault: DI status i under/over-range *)
		FaultConfig : BOOL; (* Konfiguracioni fault: parametri i range izbor *)
		ScaleSpanRaw : REAL; (* Raspon raw opsega *)
		ScaleSpanScaled : REAL; (* Raspon aktivnog skaliranog opsega *)
		ManualValueLimited : REAL; (* Ogranicena manual vrednost na aktivan opseg *)
		ActiveScaledMin : REAL; (* Donja granica aktivnog opsega *)
		ActiveScaledMax : REAL; (* Gornja granica aktivnog opsega *)
		LastGoodScaledValue : REAL; (* Poslednja validna vrednost pre promene opsega *)
		PrevRangeSelect : USINT; (* Prethodno izabrani opseg *)
		RangeChangeMem : BOOL; (* Memorija promene opsega *)
		ResetRequest : BOOL; (* Interna kopija reset komande *)
		RangeSettleTimeEffective : TIME; (* Validiran PT za tajmer stabilizacije *)
		RangeSettleTimer : TON; (* Tajmer stabilizacije posle promene opsega *)
	END_STRUCT;

	typConstAI01_DI01_DO02 : STRUCT (* Struktura konstanti i state tekstova FB_AI_01_DI_01_DO_02. *)
		ST_DISABLED : USINT := 0; (* Blok onemogucen (Enable=FALSE). *)
		ST_ACTIVE : USINT := 1; (* Normalan rad bez alarma. *)
		ST_UNDERRANGE : USINT := 2; (* Raw vrednost ispod RawMin granice. *)
		ST_OVERRANGE : USINT := 3; (* Raw vrednost iznad RawMax granice. *)
		ST_FAULT : USINT := 4; (* Latched fault stanje u automatskom radu. *)
		ST_MANUAL : USINT := 5; (* Aktivno manuelno zadavanje bez fault-a. *)
		ST_MANUAL_FAULT : USINT := 6; (* Manuelni rad uz aktivan latched fault. *)
		ST_TRANSMITTER_STATUS_0 : USINT := 7; (* Statusni DI transmitera je FALSE. *)
		ST_RANGE_CHANGING : USINT := 8; (* U toku je stabilizacija nakon promene opsega. *)
		CMT_DISABLED : STRING[80] := 'Stanje 0: transmiter neaktivan (Enable=FALSE), izlaz je na 0.0.'; (* Tekstualni opis stanja ST_DISABLED. *)
		CMT_ACTIVE : STRING[80] := 'Stanje 1: normalan rad, ulaz je u dozvoljenom opsegu, bez alarma.'; (* Tekstualni opis stanja ST_ACTIVE. *)
		CMT_UNDERRANGE : STRING[80] := 'Stanje 2: ulazna raw vrednost je ispod definisanog minimuma (RawMin).'; (* Tekstualni opis stanja ST_UNDERRANGE. *)
		CMT_OVERRANGE : STRING[80] := 'Stanje 3: ulazna raw vrednost je iznad definisanog maksimuma (RawMax).'; (* Tekstualni opis stanja ST_OVERRANGE. *)
		CMT_FAULT : STRING[80] := 'Stanje 4: prisutan je alarm (latched), potreban je ResetAlarm za potvrdu.'; (* Tekstualni opis stanja ST_FAULT. *)
		CMT_MANUAL : STRING[80] := 'Stanje 5: aktivan rucni rezim, ScaledValue dolazi iz ManualValue.'; (* Tekstualni opis stanja ST_MANUAL. *)
		CMT_MANUAL_FAULT : STRING[80] := 'Stanje 6: aktivan rucni rezim i istovremeno prisutan latched alarm.'; (* Tekstualni opis stanja ST_MANUAL_FAULT. *)
		CMT_TRANSMITTER_STATUS_0 : STRING[80] := 'Stanje 7: statusni DI signal transmitera je 0; skaliranje ostaje aktivno.'; (* Tekstualni opis stanja ST_TRANSMITTER_STATUS_0. *)
		CMT_RANGE_CHANGING : STRING[80] := 'Stanje 8: promena opsega je u toku; ceka se stabilizacija opsega.'; (* Tekstualni opis stanja ST_RANGE_CHANGING. *)
	END_STRUCT;

	typAI01_DI01_DO02 : STRUCT (* Agregatna struktura svih sekcija za FB_AI_01_DI_01_DO_02. *)
		Input : typInAI01_DI01_DO02; (* Ulazi sa izborom opsega i komandama. *)
		Param : typParAI01_DI01_DO02; (* Parametri opsega i skaliranja. *)
		Output : typOutAI01_DI01_DO02; (* Izlazi, aktivan opseg i fault status. *)
		Internal : typIntAI01_DI01_DO02; (* Interne pomocne promenljive i tajmeri. *)
		Constant : typConstAI01_DI01_DO02; (* Konstante stanja i komentari stanja. *)
	END_STRUCT;

	(* ======================================================================== *)
	(* FB_DI                                                                    *)
	(* ======================================================================== *)
	typInDI : STRUCT (* Ulazna struktura FB_DI. *)
		Enable : BOOL; (* Globalni enable FB-a *)
		SensorIn : BOOL; (* Digitalni ulaz sa terena *)
		StatusIn : BOOL; (* Statusni signal uredjaja, opciono koristi logika *)
		EnableManual : BOOL; (* TRUE = koristi ManualValue umesto SignalIn *)
		ManualValue : BOOL; (* Rucno zadat DI signal *)
		ResetAlarm : BOOL; (* Reset latched alarma *)
		ManualAlarm : BOOL; (* Spoljasnji/manual alarm signal *)
	END_STRUCT;

	typParDI : STRUCT (* Parametarska struktura FB_DI. *)
		UseStatusInput : BOOL; (* TRUE = proverava StatusIn; FALSE = ignorise ga *)
		InvertSignal : BOOL; (* TRUE = invertuje ulaznu DI vrednost *)
		DelayOn : TIME; (* Vreme potvrde OFF->ON prelaza *)
		DelayOff : TIME; (* Vreme potvrde ON->OFF prelaza *)
		AlarmOnTrue : BOOL; (* Alarm aktivan kada je Value=TRUE *)
		AlarmOnFalse : BOOL; (* Alarm aktivan kada je Value=FALSE *)
		TextTrue : STRING[80]; (* Tekst za stanje Value=TRUE *)
		TextFalse : STRING[80]; (* Tekst za stanje Value=FALSE *)
		TextAlarm : STRING[80]; (* Tekst za alarm stanje *)
		TextFault : STRING[80]; (* Tekst za fault stanje *)
	END_STRUCT;

	typOutDI : STRUCT (* Izlazna struktura FB_DI. *)
		Value : BOOL; (* Finalna DI vrednost nakon manual/invert/delay obrade *)
		Status : BOOL; (* TRUE = bez aktivnog fault uslova i Enable=TRUE *)
		Alarm : BOOL; (* Procesni alarm prema AlarmOnTrue/AlarmOnFalse *)
		Error : BOOL; (* Fault latch izlaz *)
		ManualActive : BOOL; (* TRUE kada je manual rezim aktivan *)
		State : USINT; (* Numericki kod stanja *)
		State_comment : STRING[80]; (* Tekstualni opis stanja *)
		StatusSignalIn : BOOL; (* Kopija statusnog signala za HMI/SCADA *)
		FaultLatched : BOOL; (* Memorisan fault do validnog reset-a *)
		FaultCondition : BOOL; (* Trenutni fault uslov u ovom scan-u *)
		AlarmCondition : BOOL; (* Trenutni procesni alarm uslov *)
	END_STRUCT;

	typIntDI : STRUCT (* Interna radna struktura FB_DI. *)
		SignalRaw : BOOL; (* Vrednost pre delay obrade *)
		SignalFiltered : BOOL; (* Vrednost nakon delay obrade *)
		FaultLatched : BOOL; (* Interni fault latch *)
		FaultCondition : BOOL; (* Interni fault uslov u scan-u *)
		AlarmCondition : BOOL; (* Interni procesni alarm uslov *)
		TonOn : TON; (* Delay ON tajmer *)
		TonOff : TON; (* Delay OFF tajmer *)
	END_STRUCT;

	typConstDI : STRUCT (* Struktura state konstanti FB_DI. *)
		ST_DISABLED : USINT := 0; (* Blok onemogucen. *)
		ST_AUTO_FALSE : USINT := 1; (* Auto rezim, izlazna vrednost FALSE. *)
		ST_AUTO_TRUE : USINT := 2; (* Auto rezim, izlazna vrednost TRUE. *)
		ST_AUTO_ALARM : USINT := 3; (* Auto rezim sa procesnim alarmom. *)
		ST_AUTO_FAULT : USINT := 4; (* Auto rezim sa fault stanjem. *)
		ST_MAN_FALSE : USINT := 5; (* Manual rezim, izlazna vrednost FALSE. *)
		ST_MAN_TRUE : USINT := 6; (* Manual rezim, izlazna vrednost TRUE. *)
		ST_MAN_ALARM : USINT := 7; (* Manual rezim sa procesnim alarmom. *)
		ST_MAN_FAULT : USINT := 8; (* Manual rezim sa fault stanjem. *)
	END_STRUCT;

	typDI : STRUCT (* Agregatna struktura svih sekcija za FB_DI. *)
		Input : typInDI; (* Ulazni signali, manual i reset komande. *)
		Param : typParDI; (* Parametri obrade i tekstovi stanja. *)
		Output : typOutDI; (* Finalna DI vrednost, alarm/fault i stanje. *)
		Internal : typIntDI; (* Interna logika filtracije i latch-a. *)
		Constant : typConstDI; (* Konstante state kodova DI bloka. *)
	END_STRUCT;

	(* ======================================================================== *)
	(* FB_V_ON_OFF_FB                                                           *)
	(* ======================================================================== *)
	typInVOnOff : STRUCT (* Ulazna struktura FB_V_ON_OFF_FB. *)
		Enable : BOOL; (* Globalni enable FB-a *)
		EnableManual : BOOL; (* TRUE = komanda pozicije dolazi iz manual ulaza *)
		Open_Manual : BOOL; (* Manual zahtev: TRUE otvori, FALSE zatvori *)
		OpenFb : BOOL; (* Povratni signal otvorenog krajnjeg polozaja *)
		CloseFb : BOOL; (* Povratni signal zatvorenog krajnjeg polozaja *)
		ResetAlarm : BOOL; (* Reset memorisanog alarma, samo kada trenutni fault uslov nije aktivan *)
		ManualAlarm : BOOL; (* Spoljni/manual fault zahtev *)
		ForceCmd : BOOL; (* TRUE = komanda prolazi ka ventilu i u fault stanju; FALSE = komanda blokirana (bezbedan polozaj) *)
	END_STRUCT;

	typParVOnOff : STRUCT (* Parametarska struktura FB_V_ON_OFF_FB. *)
		FbOpenExists : BOOL; (* TRUE ako fizicki postoji Open feedback signal *)
		FbCloseExists : BOOL; (* TRUE ako fizicki postoji Close feedback signal *)
		OpenMinTime : TIME; (* Minimalno dozvoljeno vreme otvaranja pre OpenFb potvrde *)
		OpenMaxTime : TIME; (* Maksimalno dozvoljeno vreme otvaranja do OpenFb potvrde *)
		CloseMinTime : TIME; (* Minimalno dozvoljeno vreme zatvaranja pre CloseFb potvrde *)
		CloseMaxTime : TIME; (* Maksimalno dozvoljeno vreme zatvaranja do CloseFb potvrde *)
		StableFbDelay : TIME; (* Delay za detekciju nestabilnog feedback-a u stabilnim stanjima *)
	END_STRUCT;

	typOutVOnOff : STRUCT (* Izlazna struktura FB_V_ON_OFF_FB. *)
		CmdOpen : BOOL; (* Komanda ka aktuatoru za otvaranje *)
		CmdClose : BOOL; (* Komanda ka aktuatoru za zatvaranje *)
		Status : BOOL; (* TRUE = bez alarma i Enable=TRUE *)
		InTransition : BOOL; (* TRUE dok je ventil u stanjima ST_OPENING ili ST_CLOSING *)
		ResetAllowed : BOOL; (* TRUE kada je dozvoljen reset latched alarma *)
		State : USINT; (* Kopija internog stanja za HMI *)
		State_comment : STRING[80]; (* Opis stanja za HMI *)
		Diag : STRING[40]; (* Kratka operativna dijagnostika za live nadzor *)
		FaultLatched : BOOL; (* Memorisan alarm, ostaje 1 do validnog reseta *)
		FaultCondition : BOOL; (* Trenutni fault uslov u ovom scan-u *)
		FaultInManual : BOOL; (* Alarm je nastao dok je bio aktivan manual mod *)
		FaultCode : USINT; (* Numericki kod alarma *)
		FaultText : STRING[80]; (* Tekst alarma za HMI *)
		ForceActive : BOOL; (* TRUE = fault aktivan ali ForceCmd premoscava blokadu komande *)
		LastOpenStartTime  : REAL; (* Vreme od Open komande do gubitka CloseFb [s]; 0.0 ako FbCloseExists=FALSE *)
		LastOpenTime       : REAL; (* Vreme od Open komande do OpenConfirm=TRUE [s]; 0.0 ako FbOpenExists=FALSE *)
		LastCloseStartTime : REAL; (* Vreme od ukidanja Open komande do gubitka OpenFb [s]; 0.0 ako FbOpenExists=FALSE *)
		LastCloseTime      : REAL; (* Vreme od ukidanja Open komande do CloseConfirm=TRUE [s]; 0.0 ako FbCloseExists=FALSE *)
	END_STRUCT;

	typIntVOnOff : STRUCT (* Interna radna struktura FB_V_ON_OFF_FB. *)
		DesiredOpen : BOOL; (* Zeljen polozaj ventila: TRUE = otvoren, FALSE = zatvoren *)
		FaultLatched : BOOL; (* Memorisan alarm - ostaje aktivan dok se ne resetuje *)
		FaultCondition : BOOL; (* Trenutno aktivan uslov alarma u ovom ciklusu *)
		FaultInManual : BOOL; (* Pamti da li je alarm nastao u rucnom modu *)
		FaultCode : USINT; (* Interni broj greske *)
		FaultText : STRING[80]; (* Tekstualni opis greske za HMI *)
		OpenConfirm : BOOL; (* Potvrda da je ventil otvoren *)
		CloseConfirm : BOOL; (* Potvrda da je ventil zatvoren *)
		Step : USINT; (* Interno stanje state machine *)
		PrevEnable : BOOL; (* Pamti prethodno stanje Enable signala zbog detekcije rising edge *)
		OpeningStarted : BOOL; (* Tokom otvaranja: ventil je poceo da se otvara *)
		ClosingStarted : BOOL; (* Tokom zatvaranja: ventil je poceo da se zatvara *)
		StableClosedFbError : BOOL; (* U stabilno zatvorenom stanju postoji greska feedback-a *)
		StableOpenedFbError : BOOL; (* U stabilno otvorenom stanju postoji greska feedback-a *)
		OpenMinTimer : TON; (* Minimalno dozvoljeno vreme otvaranja *)
		OpenMaxTimer : TON; (* Maksimalno dozvoljeno vreme otvaranja *)
		CloseMinTimer : TON; (* Minimalno dozvoljeno vreme zatvaranja *)
		CloseMaxTimer : TON; (* Maksimalno dozvoljeno vreme zatvaranja *)
		OpenMeasureTimer : TON; (* Merenje realnog trajanja otvaranja *)
		CloseMeasureTimer : TON; (* Merenje realnog trajanja zatvaranja *)
		StableClosedFbTimer : TON; (* Delay za potvrdu greske feedback-a u zatvorenom stanju *)
		StableOpenedFbTimer : TON; (* Delay za potvrdu greske feedback-a u otvorenom stanju *)
		PrevCloseFb : BOOL; (* Prethodni scan CloseFb - za detekciju falling edge u ST_OPENING *)
		PrevOpenFb  : BOOL; (* Prethodni scan OpenFb  - za detekciju falling edge u ST_CLOSING *)
	END_STRUCT;

	typCfgVOnOff : STRUCT (* Konfiguraciona struktura state/fault kodova FB_V_ON_OFF_FB. *)
		OpenMinTime_Valid : TIME; (* Validirano minimalno vreme otvaranja. *)
		OpenMaxTime_Valid : TIME; (* Validirano maksimalno vreme otvaranja. *)
		CloseMinTime_Valid : TIME; (* Validirano minimalno vreme zatvaranja. *)
		CloseMaxTime_Valid : TIME; (* Validirano maksimalno vreme zatvaranja. *)
		StableFbDelay_Valid : TIME; (* Validiran delay nadzora stabilnog feedback-a. *)

		ST_DISABLED : USINT := 0; (* Blok onemogucen. *)
		ST_IDLE_CLOSED : USINT := 10; (* Stabilno stanje: ventil zatvoren. *)
		ST_IDLE_OPENED : USINT := 20; (* Stabilno stanje: ventil otvoren. *)
		ST_OPENING : USINT := 30; (* Tranzicija otvaranja u toku. *)
		ST_CLOSING : USINT := 40; (* Tranzicija zatvaranja u toku. *)
		ST_FAULT : USINT := 90; (* Fault stanje ventila. *)

		FLT_NONE : USINT := 0; (* Nema aktivnog fault-a. *)
		FLT_MANUAL_ALARM : USINT := 1; (* Manual alarm zahtev je aktivan. *)
		FLT_FB_CONFLICT : USINT := 2; (* Konflikt feedback-a (OpenFb i CloseFb). *)
		FLT_OPEN_TIMEOUT : USINT := 3; (* Otvaranje nije potvrdjeno u OpenMaxTime. *)
		FLT_OPEN_TOO_FAST : USINT := 4; (* Otvaranje potvrdeno pre OpenMinTime. *)
		FLT_CLOSE_TIMEOUT : USINT := 5; (* Zatvaranje nije potvrdjeno u CloseMaxTime. *)
		FLT_CLOSE_TOO_FAST : USINT := 6; (* Zatvaranje potvrdeno pre CloseMinTime. *)
		FLT_STABLE_OPEN_FB : USINT := 7; (* Greska feedback-a u stabilno otvorenom stanju. *)
		FLT_STABLE_CLOSE_FB : USINT := 8; (* Greska feedback-a u stabilno zatvorenom stanju. *)
		FLT_TIME_CONFIG_INVALID : USINT := 9; (* Nevalidna konfiguracija vremenskih parametara. *)
	END_STRUCT;

	(* ======================================================================== *)
	(* FB_HV_2LS (rucni ventil sa 2 krajnja prekidaca)                         *)
	(* ======================================================================== *)
	typInHV2LS : STRUCT (* Ulazna struktura FB_HV_2LS. *)
		Enable : BOOL; (* Globalni enable FB-a *)
		CloseFb : BOOL; (* DI - krajnji prekidac ZATVORENO *)
		OpenFb : BOOL; (* DI - krajnji prekidac OTVORENO *)
		ResetAlarm : BOOL; (* Potvrda/resetovanje memorisanog alarma *)
	END_STRUCT;

	typParHV2LS : STRUCT (* Parametarska struktura FB_HV_2LS. *)
		T_OpenClose_SP : REAL; (* Max vreme tranzicije u sekundama (alarm Stanje 4) *)
		T_BothActive_SP : REAL; (* Debounce vreme za oba signala aktivna u sekundama (alarm Stanje 5) *)
	END_STRUCT;

	typOutHV2LS : STRUCT (* Izlazna struktura FB_HV_2LS. *)
		Status : BOOL; (* TRUE = aktivan i nema alarma; FALSE = neaktivan ili alarm *)
		State : USINT; (* Numericki kod stanja 0-5 *)
		State_comment : STRING[80]; (* Tekstualni opis stanja *)
		AlarmActive : BOOL; (* TRUE = alarm uslov trenutno postoji *)
		AlarmLatched : BOOL; (* TRUE = alarm zakljucan, ceka ResetAlarm *)
		FaultCode : USINT; (* Kod greske: 0=nema, 1=tranzicija timeout, 2=oba aktivna *)
		FaultText : STRING[80]; (* Tekstualni opis greske *)
	END_STRUCT;

	typIntHV2LS : STRUCT (* Interna radna struktura FB_HV_2LS. *)
		FaultLatched : BOOL; (* Memorisan alarm do validnog reset-a *)
		FaultCondition : BOOL; (* Trenutni fault uslov u ovom scan-u *)
		FaultCode : USINT; (* Interni broj greske *)
		Step : USINT; (* Interno stanje *)
		BothActiveRaw : BOOL; (* Sirovi uslov: oba DI aktivna *)
		TransitionRaw : BOOL; (* Sirovi uslov: ni jedan DI aktivan *)
		TonTransition : TON; (* Tajmer za tranziciju - predugo u medjupolozaju *)
		TonBothActive : TON; (* Tajmer za debounce oba signala aktivna *)
	END_STRUCT;

	typCfgHV2LS : STRUCT (* Konfiguraciona struktura konstanti FB_HV_2LS. *)
		T_OpenClose_Valid : TIME; (* Validirano vreme tranzicije *)
		T_BothActive_Valid : TIME; (* Validirano debounce vreme za oba signala *)
		ST_DISABLED : USINT := 0; (* Blok neaktivan *)
		ST_CLOSED : USINT := 1; (* Aktivan - zatvoren *)
		ST_OPEN : USINT := 2; (* Aktivan - otvoren *)
		ST_TRANSITION : USINT := 3; (* Aktivan - u tranziciji *)
		ST_FLT_TRANSITION_TIMEOUT : USINT := 4; (* Predugo u medjupolozaju (Alarm) *)
		ST_FLT_BOTH_ACTIVE : USINT := 5; (* Aktivna oba signala (Alarm) *)
		FLT_NONE : USINT := 0; (* Nema aktivnog fault-a *)
		FLT_TRANSITION_TIMEOUT : USINT := 1; (* Predugo u medjupolozaju *)
		FLT_BOTH_ACTIVE : USINT := 2; (* Oba krajnja prekidaca aktivna *)
	END_STRUCT;

	typHV2LS : STRUCT (* Agregatna struktura svih sekcija za FB_HV_2LS. *)
		Input : typInHV2LS; (* Ulazni signali i komande bloka. *)
		Param : typParHV2LS; (* Parametri vremena i ponasanja. *)
		Output : typOutHV2LS; (* Izlazi, status i dijagnostika. *)
		Internal : typIntHV2LS; (* Interna radna memorija i tajmeri. *)
		Cfg : typCfgHV2LS; (* Konstante state/fault kodova i validirana vremena. *)
	END_STRUCT;

	(* ======================================================================== *)
	(* EH_Flow / FB_EH                                                          *)
	(* ======================================================================== *)
	EH_input : STRUCT (* Ulazna struktura FB_EH_Flow. *)
		Enable : BOOL; (* Omogucavanje grejaca *)
		Setpoint : REAL; (* Zeljena temperatura (degC) *)
		TempIn : REAL; (* Ulazna temperatura (degC) *)
		TempOut : REAL; (* Izlazna temperatura (degC) *)
		FlowSwitch : BOOL; (* Prekidac protoka (TRUE ako ima protoka) *)
		FlowRate : REAL; (* Protok (l/s) *)
		BreakerFB : BOOL; (* Feedback od glavnog prekidaca *)
	END_STRUCT;

	EH_param : STRUCT (* Parametarska struktura FB_EH_Flow. *)
		FlowNominal : REAL; (* Nominalni protok (l/s) *)
		HeaterPower : REAL; (* Snaga pojedinacnog grejaca (kW) *)
		NumHeaters : INT; (* Broj ugradjenih grejaca *)
		ActiveFlowSwitch : BOOL; (* Aktivan flow switch *)
		ActiveFlowMeter : BOOL; (* Aktivan protokomer *)
		OutputType : INT; (* Tip izlaza: 0=analog, 1=PWM *)
		PWM_Width : REAL; (* Sirina PWM-a u sekundama *)
		AnalogMin : INT; (* Raw out min za analog *)
		AnalogMax : INT; (* Raw out max za analog *)
		ScanTime : REAL; (* Vreme skena u sekundama *)
	END_STRUCT;

	EH_output : STRUCT (* Izlazna struktura FB_EH_Flow. *)
		HeaterOn : ARRAY[0..29] OF BOOL; (* Stanje grejaca (TRUE=ON) *)
		AnalogOut : INT; (* Analogni izlaz (skaliran) *)
		PWMOut : REAL; (* PWM izlaz (0-1 duty cycle) *)
		Alarm : BOOL; (* Alarm (TRUE=alarm) *)
		PowerConsumption : REAL; (* Potrosnja energije (kW) *)
		Status : INT; (* Status FB-a: 0=RUNNING, 1=ALARM_OR_WAIT, 2=DISABLED *)
		State : USINT; (* Standardni numericki kod stanja FB-a za HMI *)
		State_comment : STRING[80]; (* Standardni tekstualni opis stanja FB-a *)
		StatusText : STRING[20]; (* Jednoznacan tekstualni opis trenutnog stanja FB-a *)
		OutputTypeText : STRING[12]; (* Tekstualni opis tipa izlaza *)
		AlarmCauseText : STRING[24]; (* Jednoznacan uzrok alarma/neaktivnosti *)
		MainBreaker : BOOL; (* Komanda glavnog prekidaca *)
	END_STRUCT;

	EH_internal : STRUCT (* Interna radna struktura FB_EH_Flow. *)
		PID_Controller : MTBasicsPID; (* PID kontroler *)
		Temp_Filter : MTFilterMovingAverage; (* Filter za temperaturu *)
		Prev_Enable : BOOL; (* Prethodno stanje Enable *)
		Demand_Percent : REAL; (* Potreba u procentima (0-100%) *)
		Timer_No_Flow : TON; (* Tajmer za nedostatak protoka *)
		Timer_Over_Temp : TON; (* Tajmer za previsoku temperaturu *)
		i : INT; (* Pomocna promenljiva za petlje *)
		Phase : REAL := 0.0; (* Faza za PWM *)
		local_phase : REAL; (* Lokalna faza za grejac *)
		Timer_Breaker_On : TON; (* Tajmer za ukljucivanje *)
		Timer_Breaker_Off : TON; (* Tajmer za iskljucivanje *)
		Breaker_On : BOOL := FALSE; (* Stanje sekvence *)
		Trig_Enable : R_TRIG; (* Rising edge za Enable *)
		Trig_BreakerFB_Fall : F_TRIG; (* Falling edge za BreakerFB *)
		Fault_Latched : BOOL := FALSE; (* Havarijski latch *)
		PID_Init_Pending : BOOL := FALSE; (* Pending reset integratora PID *)
		Filter_Init_Pending : BOOL := FALSE; (* Pending update filtera *)
		NumHeaters_Valid : INT; (* Broj grejaca ogranicen na opseg 0..MAX_HEATERS *)
	END_STRUCT;

	EH_constant : STRUCT (* Struktura konstanti i limita FB_EH_Flow. *)
		MAX_HEATERS : INT := 30; (* Maksimalan broj grejaca *)
		PID_MAX_OUT : REAL := 100.0; (* Maksimalni izlaz PID-a (%) *)
		PID_MIN_OUT : REAL := 0.0; (* Minimalni izlaz PID-a (%) *)
		PID_GAIN : REAL := 1.0; (* Pojacanje PID-a *)
		PID_INTEGRATION_TIME : REAL := 60.0; (* Vreme integracije (s) *)
		PID_DERIVATIVE_TIME : REAL := 0.0; (* Vreme derivacije (s) *)
		FILTER_LENGTH : UINT := 10; (* Duzina filtera *)
		NO_FLOW_TIMEOUT : TIME := T#10s; (* Tajmaut za nedostatak protoka *)
		OVER_TEMP_TIMEOUT : TIME := T#5s; (* Tajmaut za previsoku temp *)
		MAX_TEMP : REAL := 100.0; (* Maksimalna dozvoljena temp (degC) *)
		MIN_FLOW : REAL := 0.1; (* Minimalni protok (l/s) *)
		BREAKER_DELAY : TIME := T#2s; (* Kasnjenje za sekvencu *)
		STATUS_RUNNING : INT := 0; (* Aktivan rad bez alarma *)
		STATUS_ALARM_OR_WAIT : INT := 1; (* Alarm ili cekanje uslova za rad *)
		STATUS_DISABLED : INT := 2; (* Blok onemogucen *)
	END_STRUCT;

	EH_Type : STRUCT (* Agregatna struktura svih sekcija za FB_EH_Flow. *)
		Input : EH_input; (* Ulazi grejaca, temperature i protok. *)
		Param : EH_param; (* Parametri regulacije i tipa izlaza. *)
		Output : EH_output; (* Izlazi, status i alarm indikacije. *)
		Internal : EH_internal; (* Interna stanja regulacije i sekvenci. *)
		Constant : EH_constant; (* Konstante limita i status kodova. *)
	END_STRUCT;

	(* ======================================================================== *)
	(* FB_Pv_AI_AO (zajednicki type-ovi za FAST i SLOW varijantu)              *)
	(* ======================================================================== *)
	typInPvAiAo : STRUCT (* Ulazna struktura FB_Pv_AI_AO (FAST/SLOW). *)
		Enable : BOOL; (* Globalna dozvola rada bloka. FALSE gasi izlaz i tracking. *)
		Reset : BOOL; (* Reset fault stanja i internih tajmera/nadzora. *)
		EnableManual : BOOL; (* TRUE = koristi ManualValue_Percent, FALSE = koristi SP_Percent. *)
		ForceCmd : BOOL; (* TRUE = dozvoli prolaz komande i kada je fault aktivan. *)
		AI_Raw : INT; (* Sirova AI vrednost ventila u opsegu 0..32767. *)
		SP_Percent : REAL; (* Auto zadavanje ventila u procentima 0.0..100.0. *)
		ManualValue_Percent : REAL; (* Manuelno zadavanje ventila u procentima 0.0..100.0. *)
	END_STRUCT;

	typParPvAiAo : STRUCT (* Parametarska struktura FB_Pv_AI_AO (FAST/SLOW). *)
		HoldOutputOnFault : BOOL; (* TRUE = na fault drzi poslednji validan izlaz; FALSE = izlaz ide na 0%. *)
		DeviationOnLimit : REAL; (* Prag (%): ulazak u devijantno stanje. *)
		DeviationOffLimit : REAL; (* Prag (%): izlazak iz devijantnog stanja (histereza). *)
		DeviationTime : TIME; (* Maksimalno dozvoljeno trajanje devijacije pre fault-a. *)
	END_STRUCT;

	typOutPvAiAo : STRUCT (* Izlazna struktura FB_Pv_AI_AO (FAST/SLOW). *)
		PV_Percent : REAL; (* Skalirana procesna vrednost ventila u %. *)
		ActiveSP_Percent : REAL; (* Aktivna komanda (auto/manual) koja upravlja izlazom. *)
		AppliedOutput_Percent : REAL; (* Stvarno primenjena izlazna komanda nakon fault logike. *)
		FrozenOutput_Percent : REAL; (* Poslednja validna komanda za hold-on-fault scenario. *)
		AO_Raw : INT; (* Skalirani AO izlaz u opsegu 0..32767. *)
		DeviationPercent : REAL; (* ABS(ActiveSP - PV) u procentima. *)
		InDeviation : BOOL; (* TRUE kada je aktivno devijantno stanje. *)
		InTolerance : BOOL; (* TRUE kada je devijacija unutar DeviationOff granice. *)
		DeviationTimeout : BOOL; (* TRUE kada je devijacija trajala duze od dozvoljenog vremena. *)
		FaultActive : BOOL; (* Latched fault status bloka. *)
		ManualActive : BOOL; (* Informativno: aktivan manuelni mod. *)
		ForceActive : BOOL; (* Informativno: ForceCmd trenutno premostava fault blokadu. *)
		CommandPermitted : BOOL; (* TRUE kada komanda sme direktno na izlaz. *)
		Valid : BOOL; (* Informativno: blok je omogucen (Enable=TRUE). *)
		AI_Raw_Limited : INT; (* Ogranicena AI vrednost 0..32767. *)
		SP_Percent_Limited : REAL; (* Ogranicen auto SP 0.0..100.0. *)
		ManualValue_Limited : REAL; (* Ogranicen manuelni SP 0.0..100.0. *)
		ActiveSP_Limited : REAL; (* Ogranicena aktivna komanda 0.0..100.0. *)
		AppliedOutput_Limited : REAL; (* Ogranicena primenjena komanda 0.0..100.0. *)
		DeviationOn_Limited : REAL; (* Ogranicen prag ulaska u devijaciju. *)
		DeviationOff_Limited : REAL; (* Ogranicen prag izlaska iz devijacije. *)
		DeviationTime_Effective : TIME; (* Efektivno vreme devijacije nakon validacije parametra. *)
		DeviationElapsed : TIME; (* Proteklo vreme aktivne devijacije (ET iz tajmera). *)
		Status : BOOL; (* Standardni status: TRUE u normalnom radu bez fault-a. *)
		State : USINT; (* Standardni numericki kod stanja za HMI/SCADA. *)
		State_comment : STRING[80]; (* Standardni tekst opisa stanja. *)
	END_STRUCT;

	typIntPvAiAo : STRUCT (* Interna struktura FAST varijante FB_Pv_AI_AO. *)
		rAi : REAL; (* Pomocna REAL promenljiva za AI->% skaliranje. *)
		rAo : REAL; (* Pomocna REAL promenljiva za %->AO skaliranje. *)
		AO_Raw_Calc : INT; (* Interno izracunata AO raw vrednost pre ogranicenja. *)
		FB_DeviationTimer : TON; (* Tajmer trajanja devijantnog stanja. *)
	END_STRUCT;

	typIntPvAiAoSlow : STRUCT (* Interna struktura SLOW varijante FB_Pv_AI_AO. *)
		rAi : REAL; (* Pomocna REAL promenljiva za AI->% skaliranje. *)
		rAo : REAL; (* Pomocna REAL promenljiva za %->AO skaliranje. *)
		AO_Raw_Calc : INT; (* Interno izracunata AO raw vrednost pre ogranicenja. *)
		FB_DeviationTimer : TON; (* Tajmer trajanja devijantnog stanja. *)
		TrackTimer : TON; (* Glavni tajmer maksimalnog trajanja aktivnog poteza (Tmax). *)
		StartMoveTimer : TON; (* Tajmer cekanja inicijalnog pomeranja nakon komande. *)
		DirectionTimer : TON; (* Tajmer potvrde pogresnog smera kretanja. *)
		StallTimer : TON; (* Tajmer zastoja ventila tokom aktivnog poteza. *)
		TrackActive : BOOL; (* TRUE dok je aktivan nadzor jednog poteza ventila. *)
		TrackDirectionOpen : BOOL; (* TRUE = ocekuje se otvaranje (rast PV); FALSE = zatvaranje. *)
		MovementStarted : BOOL; (* TRUE kada je detektovano pocetno pomeranje posle komande. *)
		FaultReasonText : STRING[80]; (* Tekstualni uzrok fault-a za State_comment. *)
		PrevSP : REAL; (* Aktivni SP iz prethodnog ciklusa, za detekciju koraka. *)
		PrevPV : REAL; (* PV iz prethodnog ciklusa, za detekciju trenda/smera. *)
		PV_AtTrackStart : REAL; (* PV vrednost u trenutku starta poteza. *)
		LastProgressPV : REAL; (* Poslednja PV referenca za procenu progresa/stalla. *)
		StepDeltaPercent : REAL; (* Velicina koraka komande u %, ABS(NewSP-PrevSP). *)
		ExpectedTravelSec : REAL; (* Ocekivano vreme poteza u sekundama po velicini koraka. *)
		TminSec : REAL; (* Donja granica dozvoljenog vremena poteza. *)
		TmaxSec : REAL; (* Gornja granica dozvoljenog vremena poteza. *)
		ActualTravelSec : REAL; (* Stvarno ostvareno vreme poteza pri zavrsetku. *)
		TravelTimeOpenFull : TIME := T#120s; (* Puno vreme otvaranja 0->100%. *)
		TravelTimeCloseFull : TIME := T#120s; (* Puno vreme zatvaranja 100->0%. *)
		TimeTolerancePercent : REAL := 30.0; (* Dozvoljeno vremensko odstupanje oko Texp. *)
		StartMoveTimeout : TIME := T#5s; (* Max cekanje da ventil krene nakon nove komande. *)
		DirectionCheckTime : TIME := T#5s; (* Potvrda pogresnog smera ako traje duze od ovog vremena. *)
		StallTimeout : TIME := T#15s; (* Max dozvoljen zastoj tokom aktivnog kretanja. *)
		MovementStartDeltaPercent : REAL := 0.5; (* Minimalna promena PV (%) za potvrdu da je kretanje pocelo. *)
		PerScanProgressMinPercent : REAL := 0.05; (* Minimalni progres po ciklusu za izbegavanje stall detekcije. *)
		DirectionEpsPercent : REAL := 0.02; (* Mrtva zona za proveru smera da se filtrira sum. *)
		EnableTooFastFault : BOOL := FALSE; (* TRUE = prebrz potez tretirati kao fault, FALSE = samo info. *)
	END_STRUCT;

	typConstPvAiAo : STRUCT (* Struktura konstanti i state kodova FB_Pv_AI_AO. *)
		RAW_MIN : INT := 0; (* Donja granica sirovog AI/AO opsega. *)
		RAW_MAX : INT := 32767; (* Gornja granica sirovog AI/AO opsega. *)
		PCT_MIN : REAL := 0.0; (* Donja granica procentualnog opsega. *)
		PCT_MAX : REAL := 100.0; (* Gornja granica procentualnog opsega. *)
		MIN_DEV_TIME : TIME := T#1ms; (* Minimalno efektivno vreme devijacije. *)
		REC_DEV_ON_LIMIT : REAL := 8.0; (* Preporucen prag ulaska u devijaciju za commissioning. *)
		REC_DEV_OFF_LIMIT : REAL := 3.0; (* Preporucen prag izlaska iz devijacije za commissioning. *)
		REC_DEV_TIME : TIME := T#5s; (* Preporuceno vreme potvrde devijacije za commissioning. *)
		ST_DISABLED : USINT := 0; (* Blok nije omogucen. *)
		ST_AUTO_ACTIVE : USINT := 1; (* Normalan auto rad. *)
		ST_MANUAL_ACTIVE : USINT := 2; (* Normalan manual rad. *)
		ST_DEVIATION_ACTIVE : USINT := 3; (* Aktivno pracenje devijacije. *)
		ST_FAULT_HOLD : USINT := 4; (* Fault aktivan, izlaz hold/zero. *)
		ST_FAULT_FORCE : USINT := 5; (* Fault aktivan, ali ForceCmd dozvoljava komandu. *)
	END_STRUCT;

	typPvAiAo : STRUCT (* Agregatna struktura svih sekcija za FB_Pv_AI_AO. *)
		Input : typInPvAiAo; (* Ulazni procesni i upravljacki signali. *)
		Param : typParPvAiAo; (* Parametri ponasanja i pragovi logike. *)
		Output : typOutPvAiAo; (* Izlazi, statusi i dijagnostika bloka. *)
		Internal : typIntPvAiAo; (* Interne pomocne promenljive i tajmeri. *)
		Constant : typConstPvAiAo; (* Konstante granica, state kodovi i preporuke. *)
	END_STRUCT;

	(* ======================================================================== *)
	(* FB_PV_AO_NO_FB (proporcionalni ventil bez pozicionog feedback-a)  *)
	(* ======================================================================== *)
	typInPvAoNoFb : STRUCT (* Ulazna struktura FB_PV_AO_NO_FB. *)
		Enable : BOOL; (* Globalna dozvola rada bloka. *)
		AutoSP : REAL; (* Auto zadavanje u procentima. *)
		ManualMode : BOOL; (* TRUE = aktivan manuelni rezim. *)
		ManualOut : REAL; (* Manuelna izlazna komanda u procentima. *)
		ForceCmd : BOOL; (* TRUE = dozvola izlaza i kada je fault aktivan. *)
		ResetFault : BOOL; (* Reset latched fault stanja. *)
	END_STRUCT;

	typParPvAoNoFb : STRUCT (* Parametarska struktura FB_PV_AO_NO_FB. *)
		OutMin : REAL; (* Donja granica dozvoljenog izlaza u %. *)
		OutMax : REAL; (* Gornja granica dozvoljenog izlaza u %. *)
		RampUp : REAL; (* Maksimalni porast izlaza po ciklusu u %. *)
		RampDown : REAL; (* Maksimalni pad izlaza po ciklusu u %. *)
		OnDelay : TIME; (* Kasnjenje aktivacije izlaza iznad OutMin. *)
		OffDelay : TIME; (* Kasnjenje vracanja izlaza na OutMin. *)
		HoldOnFault : BOOL; (* TRUE = drzi poslednji validan izlaz na fault-u. *)
	END_STRUCT;

	typOutPvAoNoFb : STRUCT (* Izlazna struktura FB_PV_AO_NO_FB. *)
		AO_Cmd : REAL; (* Finalna komandna vrednost ventila u %. *)
		Status : BOOL; (* Standardni status: TRUE kada nema fault-a i Enable=TRUE. *)
		State : USINT; (* Standardni numericki kod stanja. *)
		State_comment : STRING[80]; (* Tekstualni opis stanja. *)
		FaultActive : BOOL; (* Latched fault status bloka. *)
		FaultCode : USINT; (* Numericki kod fault-a. *)
		ManualActive : BOOL; (* Informativno: manuelni rezim je aktivan. *)
		ForceActive : BOOL; (* Informativno: ForceCmd trenutno premostava fault. *)
		CmdTarget : REAL; (* Izabrana komanda pre delay/ramp obrade. *)
		CmdLimited : REAL; (* Komanda ogranicena na OutMin..OutMax. *)
		CmdDelayed : REAL; (* Komanda nakon OnDelay/OffDelay obrade. *)
		ParamInvalid : BOOL; (* TRUE kada je konfiguracija parametara nevalidna. *)
		OutMin_Effective : REAL; (* Efektivna donja granica posle validacije. *)
		OutMax_Effective : REAL; (* Efektivna gornja granica posle validacije. *)
		RampUp_Effective : REAL; (* Efektivni maksimalni porast komande po ciklusu. *)
		RampDown_Effective : REAL; (* Efektivni maksimalni pad komande po ciklusu. *)
		OnDelay_Effective : TIME; (* Efektivno kasnjenje aktivacije komande. *)
		OffDelay_Effective : TIME; (* Efektivno kasnjenje deaktivacije komande. *)
	END_STRUCT;

	typIntPvAoNoFb : STRUCT (* Interna radna struktura FB_PV_AO_NO_FB. *)
		CmdWorking : REAL; (* Interna radna komanda posle delay i ramp logike. *)
		LastHealthyCmd : REAL; (* Poslednja validna komanda bez fault-a. *)
		RiseRequest : BOOL; (* Zahtev za izlaz iznad OutMin. *)
		FallRequest : BOOL; (* Zahtev za izlaz na OutMin. *)
		OnDelayTimer : TON; (* Tajmer kasnjenja aktivacije komande. *)
		OffDelayTimer : TON; (* Tajmer kasnjenja deaktivacije komande. *)
		EpsPercent : REAL := 0.001; (* Mrtva zona za porejenje realnih vrednosti. *)
	END_STRUCT;

	typConstPvAoNoFb : STRUCT (* Struktura konstanti i state/fault kodova FB_PV_AO_NO_FB. *)
		PCT_MIN : REAL := 0.0; (* Donja granica procentualnog opsega izlaza. *)
		PCT_MAX : REAL := 100.0; (* Gornja granica procentualnog opsega izlaza. *)
		STEP_MIN : REAL := 0.0001; (* Minimalan pozitivan korak za ramp validaciju. *)
		FLT_NONE : USINT := 0; (* Nema aktivnog fault-a. *)
		FLT_PARAM_INVALID : USINT := 1; (* Parametri bloka nisu validni. *)
		ST_DISABLED : USINT := 0; (* Blok nije omogucen. *)
		ST_AUTO_ACTIVE : USINT := 1; (* Auto rezim aktivan bez fault-a. *)
		ST_MANUAL_ACTIVE : USINT := 2; (* Manual rezim aktivan bez fault-a. *)
		ST_FAULT_HOLD : USINT := 3; (* Fault aktivan i izlaz je hold/bez komande. *)
		ST_FAULT_FORCE : USINT := 4; (* Fault aktivan uz ForceCmd premoscenje. *)
	END_STRUCT;

	typPvAoNoFb : STRUCT (* Agregatna struktura svih sekcija za FB_PV_AO_NO_FB. *)
		Input : typInPvAoNoFb; (* Ulazi komandi i servisnih signala bloka. *)
		Param : typParPvAoNoFb; (* Parametri granica, rampi i fault logike. *)
		Output : typOutPvAoNoFb; (* Izlazi komande, status i dijagnostika. *)
		Internal : typIntPvAoNoFb; (* Interna radna stanja i tajmeri. *)
		Constant : typConstPvAoNoFb; (* Konstante limita, state i fault kodova. *)
	END_STRUCT;
END_TYPE

