

PROGRAM _INIT
	(* ======================================================================== *)
	(* PID_Pu_01_INIT                                                            *)
	(* U ovom tasku trenutno nema inicijalizacionih dodela.                      *)
	(* PID parametri i ulazi/izlazi se postavljaju iz HMI/visih nivoa logike.   *)
	(* ======================================================================== *)
	 
END_PROGRAM